name: App Tests

on:
  push:
    branches:
      - "*"
  pull_request:

defaults:
  run:
    # -l: use login shell (required when using Conda)
    shell: bash -l {0}

jobs:
  component_e2e_testing:
    name: E2E testing (${{ matrix.os }})

    runs-on: ${{ matrix.os-version }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
          - win64
        include:
          - os: linux
            os-version: ubuntu-latest
          - os: win64
            os-version: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: pareto-ui-env

      - name: Add project pareto version to .env file
        working-directory: ./electron/ui
        run: |
            echo REACT_APP_PARETO_VERSION=1.0.0 >> .env

      - name: get idaes extensions
        run: idaes get-extensions

      - name: Install correct branch of pareto
        working-directory: ../
        run: git clone https://github.com/project-pareto/project-pareto.git && cd project-pareto && pip install --progress-bar off .

      - name: Install electron JS dependencies
        run: |
          npm --prefix electron clean-install

      - name: Install frontendJS dependencies
        run: |
          npm --prefix electron/ui clean-install

      - name: run component tests
        run: npm --prefix electron/ui test

      - name: run backend server
        working-directory: backend/app
        run: python main.py & sleep 10

      - name: run frontend
        run: npm --prefix electron/ui start & sleep 30

      - name: Cypress e2e tests
        working-directory: electron/ui
        timeout-minutes: 24
        run: |
          npx cypress run

      - name: Upload artifact for screenshots & videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress_results-${{ matrix.os }}
            path: |
              electron/ui/cypress/screenshots/
              electron/ui/cypress/videos/

      ## post-run conda often fails for weird reasons. this is a potential solution
      ## see https://github.com/conda-incubator/setup-miniconda/issues/277#issuecomment-1431458277
      - name: Rename conda package cache
        if: runner.os == 'Windows'
        shell: bash
        run: mv "${CONDA_PKGS_DIR}" "${CONDA_PKGS_DIR}_do_not_cache"